apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.5.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
---
apiVersion: v1
kind: Secret
metadata:
  name: logstash-secret-settings
stringData:
  HELLO: Hallo
  WORLD: Welt
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  version: 8.5.0
  elasticsearchRef:
    name: elasticsearch-sample
  config:
    log.level: info
    api.http.host: "0.0.0.0"
    queue.type: memory
  pipelines:
    - pipeline.id: main
      config.string: |-
        input { exec { command => 'uptime' interval => 10 } }
        filter { 
          if ("${HELLO:}" != "") { 
            mutate { add_tag => ["keystore_working"] }
          } 
        }
        output { stdout{} }
# keystore init container
  secureSettings:
    - secretName: logstash-secret-settings
  deployment:
    podTemplate:
      spec:
        containers:
          - name: logstash
